config/routes.rb
Rails.application.routes.draw do
  root "texts#index"
  resources :texts do
    resource :read_progresses, only: [:create, :destroy]
  end
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :texts, only: %i[index show]

  resources :movies, only: :index do
    resource :watch_progresses, only: %i[create destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze

  has_many :watch_progresses, dependent: :destroy

  with_options presence: true do
    validates :genre
    validates :title
    validates :url
  end

  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5
  }

  # ===== Rails動画教材かPHP動画教材のどちらを表示するかの処理 =====
  def self.switch_movies_by_genres(params)
    if params[:genre] == "php"
      Movie.includes(:watch_progresses).where(genre: "php").order(id: :asc)
    else
      Movie.includes(:watch_progresses).where(genre: RAILS_GENRE_LIST).order(id: :asc)
    end
  end

  def watched_or_not?(user)
    watch_progresses.any? { |watch_progress| watch_progress.user_id == user.id }
  end
end

app/models/read_progress.rb
class ReadProgress < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, uniqueness: {
    scope: :text_id,
    message: "は同じテキスト教材を2回以上読破済みにはできません"
  }
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :read_progresses, dependent: :destroy
  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze

  with_options presence: true do
    validates :genre
    validates :title
    validates :content
  end

  def read_by?(user)
    read_progresses.any? { |read_progress| read_progress.user_id == user.id }
  end

  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5
  }

  def self.select_genre(params)
    if params == "php"
      where(genre: "php")
    else
      where(genre: RAILS_GENRE_LIST)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :read_progresses, dependent: :destroy
  has_many :watch_progresses, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: "test@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/watch_progress.rb
class WatchProgress < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user_id, uniqueness: {
    scope: :movie_id,
    message: "は同じ動画教材を2回以上視聴済みにはできません"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER_PAGE = 12

  def index
    @movies = Movie.switch_movies_by_genres(params).page(params[:page]).per(PER_PAGE)
  end
end

app/controllers/read_progresses_controller.rb
class ReadProgressesController < ApplicationController
  before_action :set_text

  def create
    current_user.read_progresses.create!(text_id: @text.id)
  end

  def destroy
    current_user.read_progresses.find_by(text_id: @text.id).destroy!
  end

  def set_text
    @text = Text.find(params[:text_id])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.includes(:read_progresses).select_genre(params[:genre])
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/watch_progresses_controller.rb
class WatchProgressesController < ApplicationController
  before_action :set_movie, only: %i[create destroy]

  def create
    current_user.watch_progresses.create!(movie_id: @movie.id)
  end

  def destroy
    current_user.watch_progresses.find_by(movie_id: @movie.id).destroy!
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    if controller_name == "texts" && action_name == "show"
      "mw-md"
    elsif devise_controller?
      "mw-sm"
    else
      "mw-xl"
    end
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(render_options)
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end

  private

  def render_options
    {
      filter_html: false, # htmlを無効化
      hard_wrap: true, # 改行を br 要素に変換
      link_attributes: { target: "_blank", rel: "noopener" } # リンクの設定
    }
  end

  def extensions
    {
      autolink: true, # http https ftpで始まる文字列を自動リンク
      fenced_code_blocks: true, # コードブロックを解析
      no_intra_emphasis: true, # 単語内の強調を解析しない
      tables: true, # 	テーブルを解析
      space_after_headers: true, # ヘッダーの先頭のハッシュとハッシュ名の間にスペースを要求
      hard_wrap: true, # 改行を br 要素に変換
      xhtml: true, # xhtml のタグを出力する(Render::XHTMLでは常に有効)
      lax_html_blocks: true # 複数行のコードの前後に空行が不要
      # strikethrough: true, # 取り消し線(~)を解析する
    }
  end
end

app/helpers/page_title_helper.rb
module PageTitleHelper
  PHP_PAGE_TITLE = "PHP".freeze
  RAILS_PAGE_TITLE = "Ruby/Rails".freeze

  def embed_youtube(url)
    tag.iframe(
      width: "100%",
      height: 200,
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true
    )
  end

  # ===== 動画教材のタイトルを切り替える処理 =====
  def switch_page_title
    params[:genre] == "php" ? PHP_PAGE_TITLE : RAILS_PAGE_TITLE
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-primary ">
  <%= link_to image_tag("yanbaru_expert_logo.png"),root_path %>
  <!--トグル-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown"> 
    <ul class="navbar-nav">
    
      <li class="nav-item active dropdown">
      <%= link_to "Ruby","#", class:"nav-link dropdown-toggle",id:"navbarDropdownMenuLink" , 'data-toggle': :dropdown, 'aria-haspopup': :true, 'aria-expanded': :false %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Ruby/Railsテキスト教材",texts_path, class: "dropdown-item" %>
          <%= link_to "Ruby/Rails動画教材", movies_path, class: "dropdown-item" %>
        </div>
      </li>
    
      <li class="nav-item active dropdown">
        <%= link_to "PHP", "#", class: "nav-link dropdown-toggle",id:"navbarDropdownMenuLink" ,'data-toggle': :dropdown, 'aria-haspopup': :'true', 'aria-expanded': :'false', 'id': :'header-profile' %>
         <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "PHPテキスト教材",texts_path(genre: "php"), class: "dropdown-item" %>
          <%= link_to "PHP動画教材",movies_path(genre: "php"), class: "dropdown-item" %>
         </div>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "アカウント編集", edit_user_registration_path,class:"nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "ログアウト", destroy_user_session_path,method: :delete,data: {confirm: "ログアウトしますか？"}, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to "新規登録", new_user_registration_path,class:"nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "ログイン", new_user_session_path,class:"nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post,class:"nav-link"%>
      </li>
      <% end %>

    </ul>
  </div>
</nav>
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>チーム開発 やんばるエキスパート教材クローン</title>
    <meta name="robots" content="noindex">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
  <body>
   <header>
     <%= render "layouts/header" %>
   </header>
    <main>
      <%= render "layouts/flash" %>
      <%# max_width メソッドは application_helper.rb に記載 %>
     <div class="base-container <%= max_width %>">
      <%= yield %>
     </div>
    </main>
   <footer>
   </footer> 
  </body>
</html>

app/views/movies/_movie.html.erb
<div class="col mb-3">
  <div class="card border-dark">
    <%# ===== `embed_youtube`メソッドはpage_titleヘルパーで定義 ===== %>
    <div class="card-header p-0 movie-header"><%= embed_youtube(movie.url) %></div>

    <div class="card-body movie-body">
      <div id="movie-<%= movie.id %>">
        <% if movie.watched_or_not?(current_user) %>
          <%# =====「視聴済み」の状態 ===== %>
          <%= render "movies/watch", movie: movie %>
        <% else %>
          <%# =====「視聴済みではない」状態 ===== %>
          <%= render "movies/not_watch", movie: movie %>
        <% end %>
      </div>

      <p>Lv.<%= movie_counter + @movies.offset_value + 1 %>：<%= movie.title %></p>
    </div>
  </div>
</div>

app/views/movies/_not_watch.html.erb
<%= link_to movie_watch_progresses_path(movie), method: :post, remote: true do %>
  <button type="button" class="btn btn-secondary btn-block mb-4">視聴済みにする</button>
<% end %>

app/views/movies/_watch.html.erb
<%= link_to movie_watch_progresses_path(movie), method: :delete, remote: true do %>
  <button type="button" class="btn btn-primary btn-block mb-4">視聴済みを解除</button>
<% end %>

app/views/movies/index.html.erb
<div class="text-center my-4">
  <h1><%= switch_page_title %>動画</h1>  <%# ===== page_titleヘルパー参照 ===== %>
</div>

<div class="container-fluid">
  <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1">
    <%= render @movies %>
  </div>
</div>

<div class="my-5">
  <%= paginate @movies %>
</div>

app/views/read_progresses/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'

app/views/read_progresses/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/unread", text: @text) %>'

app/views/texts/_read.html.erb
<%= link_to text_read_progresses_path(text),method: :delete, remote: true do %>
<button type="button" class="btn btn-primary btn-md btn-block">読破済みを解除</button>
<% end %>  

app/views/texts/_text.html.erb
<div class="col-12 col-md-6 col-lg-4 ">  
  <%= link_to  text_path(text.id) do %>
    <div class="card content-card border-dark mb-3 " >
        <img src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg" class="img-fluid">
        <div class="card-body text-dark ">
          <div id="text-<%= text.id %>">
            <% if text.read_by?(current_user) %>
             <%= render "read",text:text %>
            <% else %>
             <%= render "unread",text:text %>
            <% end %>
          </div>
          <p class="card-text mt-3">
          <%= text.title %>
          </p>
          <p>
          【<%= text.genre_i18n %>】
          </p>
       </div>
    </div>
  <% end %>  
</div>

app/views/texts/_unread.html.erb
 <%= link_to text_read_progresses_path(text),method: :post, remote: true do %>
 <button type="button" class="btn btn-secondary btn-md btn-block">読破済みにする</button>
 <% end %>

app/views/texts/index.html.erb
<h1 class = "text-center mt-2 mb-4">
<%= switch_page_title %>
<br class = "d-sm-none">テキスト教材
</h1> 
<div class="row">
  <%= render @texts %>
</div>

app/views/texts/show.html.erb
<h1 class = "text-center my-4" ><%= @text.title %></h1>
<%
    str = @text.content
%>
<div class="markdown">
  <%= markdown(str) %>
</div>

app/views/watch_progresses/create.js.erb
document.getElementById("movie-<%= @movie.id %>").innerHTML = "<%= j render("movies/watch", movie: @movie) %>"

app/views/watch_progresses/destroy.js.erb
document.getElementById("movie-<%= @movie.id %>").innerHTML = "<%= j render("movies/not_watch", movie: @movie) %>"